// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demo/internal/app"
	"demo/internal/pkg/infra"
	"demo/internal/pkg/repository"
	"demo/internal/pkg/service"
	"demo/internal/server/http"
)

// Injectors from wire.go:

func InitializeServer() *http.Server {
	redis := infra.NewRedisConn()
	iDeviceManager := repository.NewDeviceRedisRepo(redis)
	db := infra.NewDBConn()
	iDeviceStore := repository.NewDevicePostgresRepo(db)
	deviceUseCase := service.NewDeviceUseCase(iDeviceManager, iDeviceStore)
	appApp := app.NewApp(deviceUseCase)
	server := http.NewHttpServer(appApp)
	return server
}
